## Creating an array using numpy

In [2]:
import numpy as np
food = np.array(["samosa", "pakora", "raita"])
food

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [2]:
price = np.array([5, 5, 5]) 
price

array([5, 5, 5])

In [3]:
type(price)

numpy.ndarray

In [4]:
type(food)

numpy.ndarray

In [5]:
len(food)

3

In [6]:
len(price)

3

In [7]:
price[2]

5

In [9]:
price[0:]

array([5, 5, 5])

In [10]:
food[1]

'pakora'

In [11]:
food[0]

'samosa'

In [12]:
price.mean()

5.0

In [13]:
#zero method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
#empty (assignment either here should be empty or ans. should be 1 and why ? reason)
np.empty(5)

array([1., 1., 1., 1., 1.])

In [16]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#specific
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
#range after specific interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
#table of five
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [5]:
#linespace
np.linspace(1,100,num=10)


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [6]:
# specific your data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [7]:
np.ones(5, dtype=np.float64)

array([1., 1., 1., 1., 1.])

## Array Functions


In [10]:
a= np.array([10, 12, 15, 2, 4, 6, 100, 320, 0.5, 10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [13]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [14]:
b= np.array([10.2, 3.4, 2.6, 5.9, 91.7, 101.1])
b

array([ 10.2,   3.4,   2.6,   5.9,  91.7, 101.1])

In [19]:
c= np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,   2.6,   5.9,  91.7, 101.1])

In [21]:
c.sort()
c

array([  0.5,   2. ,   2.6,   3.4,   4. ,   5.9,   6. ,  10. ,  10.2,
        10.3,  12. ,  15. ,  91.7, 100. , 101.1, 320. ])

# 2-D arrays

In [24]:
a= np.array([[1, 2, 3, 4, 5],[5, 4, 3, 2, 1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [25]:
b= np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [27]:
c= np.array([[10,15],[45,50]])
c

array([[10, 15],
       [45, 50]])

In [29]:
d= np.concatenate((b,c), axis=0)
d

array([[ 6,  7],
       [ 8,  9],
       [10, 15],
       [45, 50]])

In [30]:
np.concatenate((b,c), axis=1)

array([[ 6,  7, 10, 15],
       [ 8,  9, 45, 50]])

In [35]:
a= np.array([[[  0,  1,  2],
            [ 10, 12, 13]],
             [[5, 6, 7],
             [8, 9, 11]],
           [[100, 101, 102],
          [110, 112, 113]]])
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[  5,   6,   7],
        [  8,   9,  11]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [37]:
#to find the numbers of dimenions
a.ndim

3

In [39]:
b = np.array([[5,6,7],
              [8,9,10],
             [11,12,13]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [40]:
b.ndim

2

In [42]:
a.size

18

In [43]:
a.shape

(3, 2, 3)

In [50]:
a= np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [51]:
#reshape
b= a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
#reshape
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [56]:
#convert 1D into 2D
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a.shape


(9,)

In [59]:
#row-wise
b= a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [60]:
b.shape

(1, 9)

In [61]:
#column-wise
c= a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [62]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a[2:6]

array([3, 4, 5, 6])

In [64]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [65]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [66]:
a.sum()

45

In [68]:
a.mean()

5.0